# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TemplateProjectSwiftUI' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'FLNavigationBar'
  # Pods for TemplateProjectSwiftUI

  target 'TemplateProjectSwiftUITests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TemplateProjectSwiftUIUITests' do
    # Pods for testing
  end

end
